- name: Install {{ package_category.key }} package groups
  community.general.pacman:
    name: "{{ package_group.packages }}"
    state: present
  loop: "{{ package_category.value }}"
  loop_control:
    loop_var: package_group
    label: "{{ package_group.name }}"
  when: package_category.key != 'optical_media' or blast_install_optical_media | bool
