- name: Check Vulkan capability
  ansible.builtin.command:
    cmd: vulkaninfo --summary
  changed_when: false
  when: "'amd' in blast_gpu_vendors"

- name: Check VA-API capability
  ansible.builtin.command:
    cmd: vainfo
  changed_when: false
  when: "'amd' in blast_gpu_vendors"
