- name: Load AMD GPU package groups
  ansible.builtin.include_vars:
    file: gpu/amd.yaml
- name: Install AMD GPU package groups
  community.general.pacman:
    name: "{{ package_group.packages }}"
    state: present
  loop: "{{ blast_amd_gpu_package_groups }}"
  loop_control:
    loop_var: package_group
    label: "{{ package_group.name }}"
- name: Check AMD GPU package for managed AMD module file
  ansible.builtin.command:
    cmd: pacman -Qq linux-firmware-amdgpu
  changed_when: false
- name: Install AMD GPU system files
  ansible.builtin.copy:
    src: gpu/amd/system/
    dest: /
    owner: root
    group: root
    mode: preserve
    directory_mode: preserve
