blast_services_always_enabled:
  - systemd-oomd.service
  - NetworkManager.service
blast_package_services:
  libvirt:
    - libvirtd.service
  cronie:
    - cronie.service
  openssh:
    - sshd.service
blast_ufw_enabled: true
blast_zram_enabled: true
